name: Create agent-standalone bundles

on:
  push:
    branches: [main, feature/*, release/agentic/*]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.actor_id == github.repository_owner_id

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          lfs: true















  pp/aws-lsp-codewhisperer-runtimes
  
  
  ip pairing so that the
  , one per platform.
  
  
  -arm64" "mac-x64" "win-x64")

  "
  
  
  build/archives/shared/clients.zip" "_artifacts/$platform/"
  build/archives/agent-standalone/$platform/servers.zip" "_artifacts/$platform/"
  
  
  /build/archives/shared/clients.zip" -d _artifacts/clients
  
  ad the folder used to
  ients.zip artifact
  
  chives/shared/clients.zip















































