name: Set up a new Release Candidate

on:
  workflow_dispatch:
    inputs:
      commitId:
        description: "Commit Id"
        default: ""
        required: true
        type: string

jobs:
  checkIfBranchExists:
    name: Check if a release candidate branch exists
    runs-on: ubuntu-latest
    env:
      releaseBranch: "release/candidate/100.100.100"
    steps:
      - name: Sync code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commitId }}

      - name: Check if remote branch exists
        run: |
          if git ls-remote --exit-code --heads origin $releaseBranch; then
            echo "Remote branch exists"
          else
            echo "Remote branch does not exist"
          fi

    #  - name: Set up release candidate branch
    #    id: setup-branch
    #    run: |
    #      git checkout -b $releaseBranch
    #      git push --set-upstream origin $releaseBranch

