name: Set up a new Release Candidate

on:
  workflow_dispatch:
    inputs:
      commitId:
        description: "Commit Id"
        default: ""
        required: true
        type: string

jobs:
  checkIfBranchExists:
    name: Check if a release candidate branch exists
    runs-on: ubuntu-latest
    env:
      releaseBranch: "release/candidate/100.100.100"
    steps:
      - name: Sync code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commitId }}
      - name: Check if release candidate branch exists
        id: release-branch
        run: |
          if git ls-remote --heads origin $releaseBranch; then
            echo "Release Candidate Branch exists"
            exit 1
          fi
          echo "Release Candidate Branch does not exist"
           # exit 0

      - name: Set up release candidate branch
        run: |
          git checkout -b $releaseBranch
          git push --set-upstream origin $releaseBranch

