name: Prerelease
on:
  # schedule:
  #     - cron: '5 5 * * *'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: false
        default: prerelease
  push:
    branches: [manodnyb/addActionForPrerelease2]
    # tags:
    #   - v[0-9]+.[0-9]+.[0-9]+

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Generate artifact
        run: |
          ./gradlew -PideProfileName=2023.3 :plugin-toolkit:intellij:buildPlugin
     
  
