name: Set up a new Release Candidate

on:
  workflow_dispatch:
    inputs:
      commitId:
        description: "Commit Id"
        default: ""
        required: true
        type: string

jobs:

  setupRcBranch:
    name: Set up a Release Candidate Branch
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: 100.100.100
      releaseBranch: "release/candidate/100.100.100"
    steps:
      - name: Sync code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commitId }}
      - name: Create Release Candidate Branch
        id: release-branch

        run: |
          git checkout -b $releaseBranch
      - name: Push new branch
        run: git push --set-upstream origin $releaseBranch
