name: Prerelease
on:
  # schedule:
  #     - cron: '5 5 * * *'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: false
        default: prerelease
  push:
    branches: [manodnyb/addActionForPrerelease2]
    # tags:
    #   - v[0-9]+.[0-9]+.[0-9]+

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'

      - name: Generate artifact
        run: |
          ./gradlew -PideProfileName=2023.3 :plugin-toolkit:intellij:buildPlugin --exclude-task buildResharperPlugin
      - name: Generate artifact
        run: |
          ./gradlew -PideProfileName=2023.2 :plugin-toolkit:intellij:buildPlugin --exclude-task buildResharperPlugin
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-toolkit
          path: ./plugins/toolkit/intellij/build/distributions/*.zip
          retention-days: 1
  publish:
    needs: [package]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Publish to GitHub Releases
        run: |
          gh release create v100.100.100 --draft --notes "Release notes" --title "Release title" --target $GITHUB_SHA plugin-toolkit/*.zip


     
  
